### ISSUE TITLE
ArgumentException in ScaleTransform() when printing

### ISSUE THREAD

**Issue by njcrawford** [njcrawford/EmbroideryReader#11]
From automated error report:
Time: 2016-03-27 12:52:47
Program: embroideryReader, Version=2.1.0.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files\NJCrawford Software\Embroidery
Reader\embroideryReader.exe
OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (Note: this is Windows 7)
OS Culture: en-US
Framework: 4.0.30319.42000

Error:
System.ArgumentException (Parameter is not valid.)
 at System.Drawing.Graphics.ScaleTransform(Single sx, Single sy,
MatrixOrder order)
 at System.Drawing.Graphics.ScaleTransform(Single sx, Single sy)
 at embroideryReader.frmMain.printDocument1_PrintPage(Object sender,
PrintPageEventArgs e)
 at
System.Drawing.Printing.PrintDocument.OnPrintPage(PrintPageEventArgs
e)
 at
System.Drawing.Printing.PrintDocument._OnPrintPage(PrintPageEventArgs
e)
 at System.Drawing.Printing.PrintController.PrintLoop(PrintDocument
document)
 at System.Drawing.Printing.PrintController.Print(PrintDocument
document)
 at System.Drawing.Printing.PrintDocument.Print()
 at embroideryReader.frmMain.printToolStripMenuItem_Click(Object
sender, EventArgs e)
 at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key,
EventArgs e)
 at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
 at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
 at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs
e)
 at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs
e, ToolStripItemEventType met)
 at System.Windows.Forms.Too
(Report clipped)

**Comment by njcrawford** [comment]
While browsing through older automated error reports, I found another instance of this crash:

Time: 2016-03-27 12:52:47
Program: embroideryReader, Version=2.1.0.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files\NJCrawford Software\Embroidery
Reader\embroideryReader.exe
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
OS Culture: en-US
Framework: 4.0.30319.42000

Error:
System.ArgumentException (Parameter is not valid.)
 at System.Drawing.Graphics.ScaleTransform(Single sx, Single sy,
MatrixOrder order)
 at System.Drawing.Graphics.ScaleTransform(Single sx, Single sy)
 at embroideryReader.frmMain.printDocument1_PrintPage(Object sender,
PrintPageEventArgs e)
 at
System.Drawing.Printing.PrintDocument.OnPrintPage(PrintPageEventArgs
e)
 at
System.Drawing.Printing.PrintDocument._OnPrintPage(PrintPageEventArgs
e)
 at System.Drawing.Printing.PrintController.PrintLoop(PrintDocument
document)
 at System.Drawing.Printing.PrintController.Print(PrintDocument
document)
 at System.Drawing.Printing.PrintDocument.Print()
 at embroideryReader.frmMain.printToolStripMenuItem_Click(Object
sender, EventArgs e)
 at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key,
EventArgs e)
 at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
 at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
 at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs
e)
 at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs
e, ToolStripItemEventType met)
 at System.Windows.Forms.Too
(Report clipped)

**Comment by njcrawford** [comment]
Possibly related to #12, given that the scale calculations were waaaaaay off. Closing until there is a report of the same issue in version > 2.2.
