### ISSUE TITLE
System.ArgumentException in ReadChar()

### ISSUE THREAD

**Issue by njcrawford** [njcrawford/EmbroideryReader#13]
Automated error report:

Time: 2016-04-11 15:02:58
Program: embroideryReader, Version=2.1.0.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files (x86)\NJCrawford
Software\Embroidery Reader\embroideryReader.exe
OS: Microsoft Windows NT 6.2.9200.0 (Probably Windows 10, based on user agent)
OS Culture: en-US
Framework: 4.0.30319.42000

Error:
System.ArgumentException (The output char buffer is too small to
contain the decoded characters, encoding 'Unicode (UTF-8)' fallback
'System.Text.DecoderReplacementFallback'.
Parameter name: chars)
 at System.Text.Encoding.ThrowCharsOverflow()
 at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder,
Boolean nothingDecoded)
 at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount,
Char* chars, Int32 charCount, DecoderNLS baseDecoder)
 at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex,
Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
 at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex,
Int32 byteCount, Char[] chars, Int32 charIndex)
 at System.IO.BinaryReader.InternalReadOneChar()
 at System.IO.BinaryReader.ReadChar()
 at PesFile.PesFile.OpenFile(String filename)
 at embroideryReader.frmMain.openFile(String filename)
 at embroideryReader.frmMain.openToolStripMenuItem_Click(Object
sender, EventArgs e)
 at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key,
EventArgs e)
 at System.Windows.Forms.ToolStripMenuItem.On
(Report clipped)

**Comment by njcrawford** [comment]
Probably fixed by 7b024e7, closing for now.
