### ISSUE TITLE
InvalidPrinterException (No printers are installed.) in print preview menu

### ISSUE THREAD

**Issue by njcrawford** [njcrawford/EmbroideryReader#14]
From automated error report:

Time: 2016-04-12 15:28:38
Program: embroideryReader, Version=2.1.0.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files (x86)\NJCrawford
Software\Embroidery Reader\embroideryReader.exe
OS: Microsoft Windows NT 6.2.9200.0 (Probably Windows 10 based on user agent)
OS Culture: en-US
Framework: 4.0.30319.42000

Error:
System.Drawing.Printing.InvalidPrinterException (No printers are
installed.)
 at System.Windows.Forms.PrintPreviewDialog.CreateHandle()
 at System.Windows.Forms.Control.get_Handle()
 at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
 at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key,
EventArgs e)
 at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
 at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
 at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs
e)
 at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
 at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs
mea)
 at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
 at System.Windows.Forms.Control.WndProc(Message& m)
 at System.Windows.Forms.ToolStrip.WndProc(Message& m)
 at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

**Comment by njcrawford** [comment]
Should be resolved by aeb8aaf, just didn't format the commit message properly.
