### ISSUE TITLE
Crash when saving settings

### ISSUE THREAD

**Issue by njcrawford** [njcrawford/EmbroideryReader#18]
I've never seen this issue myself, but I've received several crash reports showing almost the same stack trace.

Time: 2016-12-04 13:20:26
Program: embroideryReader, Version=2.2.3.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files\NJCrawford Software\Embroidery
Reader\embroideryReader.exe
OS: Windows Vista (TM) Home Premium Service Pack 2 (6.0 build 6002)
(x86)
OS Culture: en-US
Framework: 4.0.30319.34209 (x86)

Error:
System.IO.IOException (The process cannot access the file
'C:\Users\[username]\AppData\Local\NJCrawford Software\Embroidery
Reader\embroideryreader.ini' because it is being used by another
process.)
 at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
 at System.IO.File.InternalCopy(String sourceFileName, String
destFileName, Boolean overwrite, Boolean checkHost)
 at System.IO.File.Copy(String sourceFileName, String destFileName,
Boolean overwrite)
 at NJCrawford.IniFile.save()
 at embroideryReader.frmMain.Form1_FormClosing(Object sender,
FormClosingEventArgs e)
 at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
 at System.Windows.Forms.Form.WmClose(Message& m)
 at System.Windows.Forms.Form.WndProc(Message& m)
 at embroideryReader.frmMain.WndProc(Message& m)
 at
System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&
m)
 at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&
m)
 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

**Comment by njcrawford** [comment]
An earlier error report:

Time: 2016-11-14 12:09:03
Program: embroideryReader, Version=2.2.3.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files (x86)\NJCrawford
Software\Embroidery Reader\embroideryReader.exe
OS: Windows 10 Home release 1607 (6.3 build 14393) (x64)
OS Culture: en-US
Framework: 4.0.30319.42000 (x64)

Error:
System.IO.IOException (The process cannot access the file
'C:\Users\[username]\AppData\Local\NJCrawford Software\Embroidery
Reader\embroideryreader.ini' because it is being used by another
process.)
 at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
 at System.IO.File.InternalCopy(String sourceFileName, String
destFileName, Boolean overwrite, Boolean checkHost)
 at NJCrawford.IniFile.save()
 at embroideryReader.frmMain.Form1_FormClosing(Object sender,
FormClosingEventArgs e)
 at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
 at System.Windows.Forms.Form.WmClose(Message& m)
 at embroideryReader.frmMain.WndProc(Message& m)
 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

**Comment by njcrawford** [comment]
Another report from the same user as previous report:

Time: 2016-11-14 12:09:03
Program: embroideryReader, Version=2.2.3.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files (x86)\NJCrawford
Software\Embroidery Reader\embroideryReader.exe
OS: Windows 10 Home release 1607 (6.3 build 14393) (x64)
OS Culture: en-US
Framework: 4.0.30319.42000 (x64)

Error:
System.IO.IOException (The process cannot access the file
'C:\Users\[username]\AppData\Local\NJCrawford Software\Embroidery
Reader\embroideryreader.ini' because it is being used by another
process.)
 at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
 at System.IO.File.InternalCopy(String sourceFileName, String
destFileName, Boolean overwrite, Boolean checkHost)
 at NJCrawford.IniFile.save()
 at embroideryReader.frmMain.Form1_FormClosing(Object sender,
FormClosingEventArgs e)
 at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
 at System.Windows.Forms.Form.WmClose(Message& m)
 at embroideryReader.frmMain.WndProc(Message& m)
 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

**Comment by njcrawford** [comment]
Another crash report from a different user:
Time: 2016-12-17 20:35:33
Program: embroideryReader, Version=2.2.3.0, Culture=neutral,
PublicKeyToken=null
Program location: C:\Program Files (x86)\NJCrawford
Software\Embroidery Reader\embroideryReader.exe
OS: Windows 7 Professional (6.1 build 7600) (x64)
OS Culture: fr-FR
Framework: 4.0.30319.17626 (x64)

Error:
System.IO.IOException (The process cannot access the file
'C:\Users\[username]\AppData\Local\NJCrawford Software\Embroidery
Reader\embroideryreader.ini' because it is being used by another
process.)
 at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
 at System.IO.File.InternalCopy(String sourceFileName, String
destFileName, Boolean overwrite, Boolean checkHost)
 at NJCrawford.IniFile.save()
 at System.Windows.Forms.Form.WmClose(Message& m)
 at System.Windows.Forms.Form.WndProc(Message& m)
 at embroideryReader.frmMain.WndProc(Message& m)
 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

**Comment by njcrawford** [comment]
Another report of this same issue, although I didn't get full report details and stack trace this time.

The process cannot access the file
C:\Users\[username]\AppData\Local\NJCrawford Software\Embroidery
Reader\embroidery reader.ini because it is being used by another
process.

Using (user agent): Mozilla/5.0 (Windows NT 10.0; WOW64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87
Safari/537.36

**Comment by njcrawford** [comment]
I was finally able to reproduce this issue, but not with Embroidery Reader. It happened with another app using IniFile, so I'm pretty sure it doesn't have anything to do with Embroidery Reader.
