### ISSUE TITLE
System.ArgumentException: Parameter is not valid.

### ISSUE THREAD

**Issue by cgrossde** [njcrawford/EmbroideryReader#5]
This nice program worked flawlessly for a few weeks on my moms computer(Win 7 x64) but suddenly it throws an error on startup (e.g. double clicking a file to open it). I can click continue on the error dialog and then manually use 'File > open' to view a file but that's not so convenient anymore.

Here's the error, maybe you know what to do with this:
```
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
  at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
  at embroideryReader.frmMain.updateDesignImage()
  at embroideryReader.frmMain.openFile(String filename)
  at embroideryReader.frmMain.Form1_Load(Object sender, EventArgs e)
  at System.Windows.Forms.Form.OnLoad(EventArgs e)
  at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
  at System.Windows.Forms.Control.CreateControl()
  at System.Windows.Forms.Control.WmShowWindow(Message& m)
  at System.Windows.Forms.Control.WndProc(Message& m)
  at System.Windows.Forms.Form.WndProc(Message& m)
  at embroideryReader.frmMain.WndProc(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
embroideryReader
   Assembly Version: 2.0.0.0
   Win32 Version: 2.0.0.0
   CodeBase: file:///C:/Program%20Files%20(x86)/NJCrawford%20Software/Embroidery%20Reader/embroideryReader.exe
----------------------------------------
System.Windows.Forms
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
IniFile
   Assembly Version: 2.2.0.0
   Win32 Version: 2.2.0.0
   CodeBase: file:///C:/Program%20Files%20(x86)/NJCrawford%20Software/Embroidery%20Reader/IniFile.DLL
----------------------------------------
System.Configuration
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PesFile
   Assembly Version: 1.2.0.0
   Win32 Version: 1.2.0.0
   CodeBase: file:///C:/Program%20Files%20(x86)/NJCrawford%20Software/Embroidery%20Reader/PesFile.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
   <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by njcrawford** [comment]
Hi Chris,
Thank you for opening an issue for this! After looking into it, there appear to be some cases where the image scaling code calculates a negative size for the output bitmap. I'll try to get an update out in the next week or so to fix this issue.

**Comment by cgrossde** [comment]
Thanks! If you want me to test it, just supply me with a release.

**Comment by njcrawford** [comment]
Hi Chris,
Could you test this beta release and let me know if it fixes the problem you're seeing?
https://github.com/njcrawford/EmbroideryReader/releases/tag/v2.0.1-beta

**Comment by cgrossde** [comment]
After installing the new release and opening the first file I saw this.
![bildschirmfoto 2016-01-08 um 16 01 09](https://cloud.githubusercontent.com/assets/2333584/12229916/62bfecd2-b84c-11e5-840c-3ecdaf68bd91.png)

After expanding the window it looks like this:
![bildschirmfoto 2016-01-08 um 16 01 01](https://cloud.githubusercontent.com/assets/2333584/12229917/62c16094-b84c-11e5-932f-d13ec9a02b4a.png)

Seems to be some translation problem?

**Comment by njcrawford** [comment]
I did see the missing translation problem a couple of times while I was testing. I don't think it's related to the crashing, so I've opened issue #6 to track that one.

I'll look into the tiny window problem... I'm guessing a bad window size value was saved in the settings file, and that's probably what caused the earlier crashes.

**Comment by cgrossde** [comment]
I think you are right with the tiny window problem. I remember having a tiny window before.

**Comment by njcrawford** [comment]
I released a new version a couple days ago, but forgot to update this issue. Can you test with version 2.0.2 and see if it fixes the problem?
(link to download page for convenience: http://www.njcrawford.com/programs/embroidery-reader/ )

**Comment by njcrawford** [comment]
Hi Chris,
Is this still an issue for you? If so, could you try it with version 2.1.0 and see if it still occurs?

**Comment by cgrossde** [comment]
No, I think this is solved. Thanks :+1:
