### ISSUE TITLE
Trying to run from Windows Installer directory

### ISSUE THREAD

**Issue by njcrawford** [njcrawford/EmbroideryReader#9]
According to automated error reports, it appears that Embroidery Reader tries to run from C:\Windows\Installer\{GUID}\embroideryReader.exe instead of the correct program files location. Currently the only OS that this seems to happen on is Windows 8.

From investigating other folders under C:\Windows\Installer, it appears that it keeps a copy of any icon files in this folder.

Possible change to help avoid this issue in the future: change Wix installer to use a .ico file for the icon instead of the .exe.

**Comment by njcrawford** [comment]
More details:
Program: embroideryReader, Version=2.1.0.0, Culture=neutral,
PublicKeyToken=null

Stack trace:
System.IO.FileNotFoundException (Could not load file or assembly
'IniFile, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' or
one of its dependencies. The system cannot find the file specified.)
 at embroideryReader.EmbroideryReaderSettings..ctor()
 at embroideryReader.frmMain..ctor()
 at embroideryReader.Program.Main()

**Comment by njcrawford** [comment]
Adding another case from automated error report:

Time: 2016-04-01 15:54:15
Program: embroideryReader, Version=2.1.0.0, Culture=neutral,
PublicKeyToken=null
Program location:
C:\Windows\Installer\{857EB1E7-7BAE-4829-8178-7D9D95635CBC}\embroideryReader.exe
OS: Microsoft Windows NT 6.2.9200.0 (Note: This is Windows 8, possibly 8.1)
OS Culture: en-US
Framework: 4.0.30319.42000

Error:
System.IO.FileNotFoundException (Could not load file or assembly
'IniFile, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' or
one of its dependencies. The system cannot find the file specified.)
 at embroideryReader.EmbroideryReaderSettings..ctor()
 at embroideryReader.frmMain..ctor()
 at embroideryReader.Program.Main()

**Comment by njcrawford** [comment]
This should be completely resolved by 3c9ff41.
